[package]
name = "vaults"
version = "1.2.0"

[dependencies]
Farming = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/stable_farming", rev = "mainnet-v1.52.1" }

[addresses]
vaults = "0xd3453d9be7e35efe222f78a810bb3af1859fd1600926afced8b4936d825c9a05"

[r.mvr]
network = "mainnet"
