[package]
name = "StableFarming"
version = "mainnet-v1.0.2"
published-at = "0x585381670c3d7c1f78caeb6c803f449442659743f4047a01b942da08bbfa19f6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.35.1", override = true }
CetusClmm = { local = "../cetus_clmm/" }

[addresses]
stable_farming = "0x11ea791d82b5742cc8cab0bf7946035c97d9001d7c3803a93f119753da66f526"
