# testnet
# --------------------------
[package]
name = "CetusClmm"
version = "0.0.1"
published-at = "0x5355ed41fcf78c8bd9889429b29ac698590fbd3aba9f60cd7924d4abae1194d4"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-0.32.0" }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "sui-testnet" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-testnet" }

[addresses]

# testnet
integer_mate = "0xba60132bb7dcf93dcf1e732b51570e2d69b982fa0352d68cd60385a0cf60a17d"
move_stl = "0x877115ff36a32e050644e73808be1bd5ea4aa79fc6254f6bcda99dc3ca40ccad"
cetus_clmm = "0xb7e7513751376aed2e21b267ef6edebe806a27c979870d3575658dd443ac4248"
