# testnet
# --------------------------
[package]
name = "CetusClmm"
version = "0.0.1"
published-at = "0xc1f7a372904a2742a8c7cd37f2d67c3d37c376fcb4aaeabe6ee802cc267dd68a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-0.32.0" }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "sui-testnet-0.32.0" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-testnet-0.32.0" }

[addresses]

# testnet
integer_mate = "0xba60132bb7dcf93dcf1e732b51570e2d69b982fa0352d68cd60385a0cf60a17d"
move_stl = "0x877115ff36a32e050644e73808be1bd5ea4aa79fc6254f6bcda99dc3ca40ccad"
cetus_clmm = "0xb7e7513751376aed2e21b267ef6edebe806a27c979870d3575658dd443ac4248"
