[package]
name = "LpBurn"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
CetusClmm = { local = "../cetus_clmm/" }

[addresses]
lp_burn = "0x0"
