[package]
name = "LpBurn"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x63f7b16b3d828d8cc34ab49bb9b7da0432b06c925701fa07360388aef2dce83b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.35.1", override = true }
CetusClmm = { local = "../cetus_clmm/" }

[addresses]
lp_burn = "0x3b494006831b046481c8046910106e2dfbe0d1fa9bc01e41783fb3ff6534ed3a"
