[package]
name = "DCA"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "mainnet-v1.3.0", override = true }

[addresses]
dca = "0x587614620d0d30aed66d86ffd3ba385a661a86aa573a4d579017068f561c6d8f"
